export default {
  KOOK_HELPER_LITE_CONFIG: 'KOOK_HELPER_LITE_CONFIG',
  KOOK_HELPER_LITE_PREVIOUS_VERSION: 'KOOK_HELPER_LITE_PREVIOUS_VERSION',
  // 字体
  KOOK_HELPER_LITE_PARAGRAPH_FONT: 'KOOK_HELPER_LITE_PARAGRAPH_FONT',
  // 头像圆角
  KOOK_HELPER_LITE_AVATAR_RADIUS: 'KOOK_HELPER_LITE_AVATAR_RADIUS',
  // 左下动态头像
  KOOK_HELPER_LITE_AVATAR_DYNAMIC: 'KOOK_HELPER_LITE_AVATAR_DYNAMIC',
  // 个人简介
  KOOK_HELPER_LITE_INTRO_SCROLL: 'KOOK_HELPER_LITE_INTRO_SCROLL',
  KOOK_HELPER_LITE_INTRO_ENHANCE: 'KOOK_HELPER_LITE_INTRO_ENHANCE',
  // 平滑过滤
  KOOK_HELPER_LITE_HOVER_SMOOTH: 'KOOK_HELPER_LITE_HOVER_SMOOTH',
  // 盘古之白
  KOOK_HELPER_LITE_PANGU_SPACE: 'KOOK_HELPER_LITE_PANGU_SPACE',
  // 设置面板过滤
  KOOK_HELPER_LITE_SETTINGS_TRANSITION: 'KOOK_HELPER_LITE_SETTINGS_TRANSITION',
  // 头像框过滤
  KOOK_HELPER_LITE_CONCISE_AVATAR_FRAME: 'KOOK_HELPER_LITE_CONCISE_AVATAR_FRAME',
  // 用户列表 BUFF icon
  KOOK_HELPER_LITE_CONCISE_BUFF_ICON: 'KOOK_HELPER_LITE_CONCISE_BUFF_ICON',
}
