export default {
  KOOK_KIT_CONFIG: 'KOOK_KIT_CONFIG',
  KOOK_KIT_FIRST_LAUNCH: 'KOOK_KIT_FIRST_LAUNCH',
  KOOK_KIT_VERSION: 'KOOK_KIT_VERSION',
  KOOK_KIT_PARAGRAPH_FONT: 'KOOK_KIT_PARAGRAPH_FONT',
  KOOK_KIT_AVATAR_RADIUS: 'KOOK_KIT_AVATAR_RADIUS',
  KOOK_KIT_AVATAR_DYNAMIC: 'KOOK_KIT_AVATAR_DYNAMIC',
}
